// untuk menambahkan gunakan (+)
// untuk mengurangkan gunakan (-)
// untuk mengalikan gunakan (*)
// untuk membagi gunakan (/)
// untuk mencari sisa bagi (%)
// untuk pangkat/akar pangkat (**)
// untuk menambah kan 1 gunakan (++)
// untuk mengurangkan 1 gunakan (--)
// untuk menyatakan nilai sama (==)
// untuk menyatakan nilai sama dan dengan tipe nya (===)
// untuk menyatakan nilai tidak sama (!=)
// untuk menyatakan nilai tidak sama dengan tipe (!==)
// untuk membuat hasil true maka hasil result harus sama (&)
// untuk membuat hasil true maka hasil akhir harus true jika ada perbedaan didalam tidak apa apa(||)
